### ISSUE TITLE
确认可编译运行

### ISSUE THREAD

**Issue by billcxx** [sijintech/OpenDC#1]
因为后面我们会逐渐跟OpenCorr为了后面方便开发，我新开了这个repo，同时删掉了一些没用的部分，所以需要重新稍微测试一下。
我调整了：
1. examples里的数据打包成zip
2. external里的两个包都只保留了头文件，所以他们里面的cmake文件可以简化一下。用add_library( XXX interface）这样
3. markdown文件我都放到了docs里，请使用 https://starlight.astro.build/getting-started/ 把这个文档网站准备一下。先补充一点使用cmake编译程序的方法，后续我们再丰富内容。

**Comment by xiaotantanya** [comment]
1. cmake文件修改了一部分，删除了其中关于测试的部分，由于opencv4有用到eigen中unsupported文件夹中的头文件，所以将unsupported文件夹加了回来，同时eigen需要至少c++14标准，修改了examples文件夹CMakeLists.txt中设定的c++11标准指令。目前已经成功编译。
2. docs文档网站后续准备。

**Comment by xiaotantanya** [comment]
docs文档先补充了使用cmake编译程序的方法
